fail_fast: False

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: ["--exit-non-zero-on-fix", "--preview"]
      - id: ruff-format
        args: ["--preview"]
