version: "3.5"

services:
  hackathon_backend:
    build: .
    volumes:
      - .:/hackathon_backend
    expose:
      - 8080:8080
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations \
      && python manage.py migrate \
      && python manage.py collectstatic --noinput \
      && gunicorn hackathon_test_task.wsgi:application --bind 0.0.0.0:8080
    depends_on:
      - hackathon_backend_db

  hackathon_backend_db:
    image: postgres:14.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 1337:80
    depends_on:
      - hackathon_backend


volumes:
  postgres_data: